default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: scaffold_development
test:
  <<: *default
  database: scaffold_test
production:
  <<: *default
  database: scaffold_production
  username: scaffold
  password: <%= ENV['SCAFFOLD_DATABASE_PASSWORD'] %>
